use super::{
    create_schema_sql, create_table_sql, drop_schema_sql, drop_table_sql, rename_table_sql, NewPgColumn, NewPgTable,
};
use crate::error::AppError;

fn column(name: &str, data_type: &str) -> NewPgColumn {
    NewPgColumn { name: name.into(), data_type: data_type.into(), nullable: true, primary_key: false, identity: false }
}

fn table(columns: Vec<NewPgColumn>) -> NewPgTable {
    NewPgTable { schema: "public".into(), name: "widgets".into(), columns }
}

fn validation(result: Result<String, AppError>) -> String {
    match result {
        Err(AppError::Validation(message)) => message,
        other => panic!("expected a validation error, got {other:?}"),
    }
}

#[test]
fn quotes_every_name_in_schema_and_table_statements() {
    assert_eq!(create_schema_sql(" sales ").unwrap(), r#"CREATE SCHEMA "sales""#);
    assert_eq!(drop_schema_sql("Sales", false).unwrap(), r#"DROP SCHEMA "Sales""#);
    assert_eq!(drop_schema_sql("sales", true).unwrap(), r#"DROP SCHEMA "sales" CASCADE"#);
    assert_eq!(drop_table_sql("public", "order items", true).unwrap(), r#"DROP TABLE "public"."order items" CASCADE"#);
    assert_eq!(
        rename_table_sql("public", "old", " new ").unwrap(),
        r#"ALTER TABLE "public"."old" RENAME TO "new""#,
    );
}

#[test]
fn a_quote_inside_a_name_is_doubled_not_closed() {
    assert_eq!(drop_table_sql("public", r#"x"; DROP TABLE y; --"#, false).unwrap(), r#"DROP TABLE "public"."x""; DROP TABLE y; --""#);
}

#[test]
fn an_empty_name_is_refused() {
    assert!(create_schema_sql("  ").is_err());
    assert!(rename_table_sql("public", "old", "").is_err());
}

#[test]
fn builds_a_table_with_a_single_primary_key_and_identity() {
    let mut id = column("id", "bigint");
    id.primary_key = true;
    id.identity = true;
    let mut name = column("name", "text");
    name.nullable = false;
    let sql = create_table_sql(&table(vec![id, name, column("price", "numeric(10,2)")])).unwrap();
    assert_eq!(
        sql,
        "CREATE TABLE \"public\".\"widgets\" (\n  \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n  \"name\" text NOT NULL,\n  \"price\" numeric(10,2),\n  PRIMARY KEY (\"id\")\n)",
    );
}

#[test]
fn a_composite_key_is_one_table_constraint() {
    let mut a = column("order_id", "int");
    a.primary_key = true;
    let mut b = column("line", "int");
    b.primary_key = true;
    let sql = create_table_sql(&table(vec![a, b])).unwrap();
    assert!(sql.contains(r#"PRIMARY KEY ("order_id", "line")"#), "{sql}");
}

#[test]
fn a_table_without_a_key_has_no_key_constraint() {
    let sql = create_table_sql(&table(vec![column("note", "text")])).unwrap();
    assert!(!sql.contains("PRIMARY KEY"), "{sql}");
}

#[test]
fn refuses_tables_that_cannot_be_built() {
    assert_eq!(validation(create_table_sql(&table(vec![]))), "A table needs at least one column.");
    let mut unnamed = table(vec![column("a", "int")]);
    unnamed.name = " ".into();
    assert_eq!(validation(create_table_sql(&unnamed)), "A table needs a name.");
    assert_eq!(validation(create_table_sql(&table(vec![column(" ", "int")]))), "Every column needs a name.");
    assert_eq!(validation(create_table_sql(&table(vec![column("a", " ")]))), "Column \"a\" needs a type.");
    assert_eq!(
        validation(create_table_sql(&table(vec![column("a", "int"), column(" a ", "text")]))),
        "Column \"a\" is listed twice.",
    );
}
