use crate::error::AppError;
use serde::Deserialize;
use tauri::State;

use super::{quote_ident, AppContext};

/// One column of `create_pg_table`. The type is text the user typed (`numeric(10,2)`,
/// `text[]`, …) — checked against the server before it is spliced (see `check_types`).
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NewPgColumn {
    pub name: String,
    pub data_type: String,
    pub nullable: bool,
    pub primary_key: bool,
    /// `GENERATED BY DEFAULT AS IDENTITY` — what `serial` is shorthand for, and
    /// `serial` itself isn't a type `to_regtype` accepts.
    pub identity: bool,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NewPgTable {
    pub schema: String,
    pub name: String,
    pub columns: Vec<NewPgColumn>,
}

fn qualified(schema: &str, name: &str) -> Result<String, AppError> {
    Ok(format!("{}.{}", quote_ident(schema)?, quote_ident(name)?))
}

fn cascade(on: bool) -> &'static str {
    if on { " CASCADE" } else { "" }
}

pub(crate) fn create_schema_sql(name: &str) -> Result<String, AppError> {
    Ok(format!("CREATE SCHEMA {}", quote_ident(name.trim())?))
}

pub(crate) fn drop_schema_sql(name: &str, cascade_on: bool) -> Result<String, AppError> {
    Ok(format!("DROP SCHEMA {}{}", quote_ident(name)?, cascade(cascade_on)))
}

pub(crate) fn drop_table_sql(schema: &str, table: &str, cascade_on: bool) -> Result<String, AppError> {
    Ok(format!("DROP TABLE {}{}", qualified(schema, table)?, cascade(cascade_on)))
}

pub(crate) fn rename_table_sql(schema: &str, table: &str, new_name: &str) -> Result<String, AppError> {
    Ok(format!("ALTER TABLE {} RENAME TO {}", qualified(schema, table)?, quote_ident(new_name.trim())?))
}

fn invalid(message: &str) -> AppError {
    AppError::Validation(message.to_string())
}

/// The CREATE TABLE text. Column types go in as typed, so this must only ever run on a
/// table whose types `check_types` has accepted.
pub(crate) fn create_table_sql(table: &NewPgTable) -> Result<String, AppError> {
    if table.name.trim().is_empty() {
        return Err(invalid("A table needs a name."));
    }
    if table.columns.is_empty() {
        return Err(invalid("A table needs at least one column."));
    }
    let mut seen = std::collections::HashSet::new();
    let mut lines = Vec::new();
    for column in &table.columns {
        let name = column.name.trim();
        if name.is_empty() {
            return Err(invalid("Every column needs a name."));
        }
        if !seen.insert(name) {
            return Err(AppError::Validation(format!("Column \"{name}\" is listed twice.")));
        }
        if column.data_type.trim().is_empty() {
            return Err(AppError::Validation(format!("Column \"{name}\" needs a type.")));
        }
        let mut line = format!("{} {}", quote_ident(name)?, column.data_type.trim());
        if column.identity {
            line.push_str(" GENERATED BY DEFAULT AS IDENTITY");
        }
        // A key column is NOT NULL anyway; saying so keeps the statement honest.
        if !column.nullable || column.primary_key {
            line.push_str(" NOT NULL");
        }
        lines.push(line);
    }
    let keys: Vec<&NewPgColumn> = table.columns.iter().filter(|c| c.primary_key).collect();
    if !keys.is_empty() {
        let mut quoted = Vec::new();
        for column in keys {
            quoted.push(quote_ident(column.name.trim())?);
        }
        lines.push(format!("PRIMARY KEY ({})", quoted.join(", ")));
    }
    Ok(format!(
        "CREATE TABLE {} (\n  {}\n)",
        qualified(&table.schema, table.name.trim())?,
        lines.join(",\n  "),
    ))
}

// A type can't be quoted like a name, so each one is put to the server's own parser
// first: `to_regtype` accepts exactly one type name (with its modifiers and `[]`) and
// answers NULL or a syntax error for anything else — so text that passes is a type and
// nothing more.
async fn check_types(tx: &mut sqlx::PgConnection, columns: &[NewPgColumn]) -> Result<(), AppError> {
    for column in columns {
        let found: Option<String> = match sqlx::query_scalar("SELECT to_regtype($1)::text")
            .bind(column.data_type.trim())
            .fetch_one(&mut *tx)
            .await
        {
            Ok(val) => val,
            Err(sqlx::Error::Database(e)) if e.code().as_deref() == Some("42601") => None,
            Err(e) => return Err(AppError::Postgres(e)),
        };
        if found.is_none() {
            return Err(AppError::Validation(format!(
                "\"{}\" isn't a type this server knows (column \"{}\").",
                column.data_type.trim(),
                column.name.trim(),
            )));
        }
    }
    Ok(())
}

// DDL waits for every lock on the table, including one held by a tab's own open
// transaction — and that tab only closes once the drop succeeds. A short lock timeout
// turns that wait into an error the user can act on instead of a hang.
async fn execute_ddl(pool: &sqlx::PgPool, sql: String, columns: &[NewPgColumn]) -> Result<(), AppError> {
    let mut tx = match pool.begin().await {
        Ok(val) => val,
        Err(e) => return Err(AppError::Postgres(e)),
    };
    if let Err(e) = sqlx::query("SET LOCAL lock_timeout = '5s'").execute(&mut *tx).await {
        return Err(AppError::Postgres(e));
    }
    check_types(&mut tx, columns).await?;
    if let Err(e) = sqlx::query(sqlx::AssertSqlSafe(sql)).execute(&mut *tx).await {
        return Err(AppError::Postgres(e));
    }
    match tx.commit().await {
        Ok(_) => Ok(()),
        Err(e) => Err(AppError::Postgres(e)),
    }
}

pub(crate) async fn create_schema_impl(pool: &sqlx::PgPool, name: &str) -> Result<(), AppError> {
    execute_ddl(pool, create_schema_sql(name)?, &[]).await
}

pub(crate) async fn drop_schema_impl(pool: &sqlx::PgPool, name: &str, cascade_on: bool) -> Result<(), AppError> {
    execute_ddl(pool, drop_schema_sql(name, cascade_on)?, &[]).await
}

pub(crate) async fn create_table_impl(pool: &sqlx::PgPool, table: &NewPgTable) -> Result<(), AppError> {
    execute_ddl(pool, create_table_sql(table)?, &table.columns).await
}

pub(crate) async fn drop_table_impl(pool: &sqlx::PgPool, schema: &str, table: &str, cascade_on: bool) -> Result<(), AppError> {
    execute_ddl(pool, drop_table_sql(schema, table, cascade_on)?, &[]).await
}

pub(crate) async fn rename_table_impl(pool: &sqlx::PgPool, schema: &str, table: &str, new_name: &str) -> Result<(), AppError> {
    execute_ddl(pool, rename_table_sql(schema, table, new_name)?, &[]).await
}

#[tauri::command]
pub async fn create_pg_schema(ctx: State<'_, AppContext>, id: String, name: String) -> Result<(), AppError> {
    let pool = ctx.pg_pool_for_write(&id).await?;
    create_schema_impl(&pool, &name).await
}

#[tauri::command]
pub async fn drop_pg_schema(ctx: State<'_, AppContext>, id: String, name: String, cascade: bool) -> Result<(), AppError> {
    let pool = ctx.pg_pool_for_write(&id).await?;
    drop_schema_impl(&pool, &name, cascade).await
}

#[tauri::command]
pub async fn create_pg_table(ctx: State<'_, AppContext>, id: String, table: NewPgTable) -> Result<(), AppError> {
    let pool = ctx.pg_pool_for_write(&id).await?;
    create_table_impl(&pool, &table).await
}

#[tauri::command]
pub async fn drop_pg_table(ctx: State<'_, AppContext>, id: String, schema: String, table: String, cascade: bool) -> Result<(), AppError> {
    let pool = ctx.pg_pool_for_write(&id).await?;
    drop_table_impl(&pool, &schema, &table, cascade).await
}

#[tauri::command]
pub async fn rename_pg_table(
    ctx: State<'_, AppContext>,
    id: String,
    schema: String,
    table: String,
    new_name: String,
) -> Result<(), AppError> {
    let pool = ctx.pg_pool_for_write(&id).await?;
    rename_table_impl(&pool, &schema, &table, &new_name).await
}

#[cfg(test)]
#[path = "ddl.test.rs"]
mod tests;
