//! Live-PostgreSQL coverage of `list_columns_impl`'s identity/generated
//! classification (`ozendb-96o.1`) — split into its own file rather than grown
//! into `pg_command_integration_tests.rs`, mirroring how that file itself was
//! split out of `pg_integration_tests.rs`. Shares that file's `test_config`/
//! `pool` helpers and skip behavior; see its module doc comment for how to run
//! these.

use crate::commands::list_columns_impl;
use crate::pg_integration_tests::{pool, test_config};

#[tokio::test]
async fn classifies_identity_and_generated_columns() {
    let config = match test_config() {
        Some(val) => val,
        None => {
            eprintln!("skipping: set OZENDB_TEST_POSTGRES=host[:port] to run live tests");
            return;
        }
    };
    let pool = pool(&config).await;

    for stmt in [
        "DROP SCHEMA IF EXISTS ozendb_it_ident CASCADE",
        "CREATE SCHEMA ozendb_it_ident",
        "CREATE TABLE ozendb_it_ident.t ( \
            id SERIAL PRIMARY KEY, \
            always_id INT GENERATED ALWAYS AS IDENTITY, \
            default_id INT GENERATED BY DEFAULT AS IDENTITY, \
            computed INT GENERATED ALWAYS AS (id + 1) STORED, \
            plain TEXT NOT NULL \
        )",
    ] {
        match sqlx::query(stmt).execute(&pool).await {
            Ok(_) => {}
            Err(e) => panic!("setup ({stmt}): {e}"),
        }
    }

    let columns = list_columns_impl(&pool, "ozendb_it_ident", "t").await.unwrap();
    let by_name: std::collections::HashMap<&str, _> =
        columns.iter().map(|c| (c.name.as_str(), c)).collect();

    // A plain serial is a DEFAULT nextval(...), not an identity column — the two
    // must stay distinguishable, since INSERT treats them the same way but the
    // schema-read must not conflate them.
    assert_eq!(by_name["id"].identity, None);
    assert!(by_name["id"].default.as_deref().unwrap_or("").contains("nextval"));

    assert_eq!(by_name["always_id"].identity.as_deref(), Some("always"));
    assert_eq!(by_name["default_id"].identity.as_deref(), Some("by_default"));

    // A STORED generated column is neither an identity column nor an ordinary
    // default — INSERT must never target it at all.
    assert_eq!(by_name["computed"].generated.as_deref(), Some("stored"));
    assert_eq!(by_name["computed"].identity, None);

    assert_eq!(by_name["plain"].identity, None);
    assert_eq!(by_name["plain"].generated, None);
    assert!(!by_name["plain"].nullable);

    sqlx::query("DROP SCHEMA ozendb_it_ident CASCADE").execute(&pool).await.ok();
}
