<script setup>
import { ref, computed } from 'vue'
import { createTable } from '../api/ddl'
import { COMMON_TYPES, newColumn, startingColumns, tableRequest, draftProblem } from './tableDraft'
import BaseModal from '../../../components/base/BaseModal.vue'
import BaseInput from '../../../components/base/BaseInput.vue'
import BaseButton from '../../../components/base/BaseButton.vue'
import BaseCheckbox from '../../../components/base/BaseCheckbox.vue'
import FieldError from '../../../components/base/FieldError.vue'
import HintText from '../../../components/base/HintText.vue'
import { errText } from '../../../utils/errors'
import { showToast } from '../../../stores/toast'
import { invalidateConnectionResources } from '../../../stores/connectionData'
import { openPostgresTable } from '../../../stores/tabCreators'

// Schema → Create Table…: a name and a column list, and the new table opens in a tab.
const props = defineProps({
  target: { type: Object, required: true },   // { connId, connName, database, schema }
})
const emit = defineEmits(['close'])

const name = ref('')
const columns = ref(startingColumns())
const error = ref(null)
const saving = ref(false)
const problem = computed(() => draftProblem(name.value, columns.value))

function addColumn() {
  columns.value.push(newColumn())
}

function removeColumn(index) {
  columns.value.splice(index, 1)
}

async function confirm() {
  if (problem.value || saving.value) return
  saving.value = true
  error.value = null
  const { connId, connName, database, schema } = props.target
  const request = tableRequest(schema, name.value, columns.value)
  try {
    await createTable(connId, request)
    invalidateConnectionResources(connId)
    showToast(`Table "${request.name}" created`)
    openPostgresTable({ connectionId: connId, connectionName: connName, database, schema, table: request.name })
    emit('close')
  } catch (e) {
    error.value = errText(e)
  } finally {
    saving.value = false
  }
}
</script>

<template>
  <BaseModal title="Create Table" width="680px" @close="emit('close')">
    <div class="del-body">
      <BaseInput v-model="name" class="prompt-input" :placeholder="`Table name in ${target.schema}`" />
      <div class="ct-grid">
        <span class="ct-head">Column</span><span class="ct-head">Type</span>
        <span class="ct-head">Not null</span><span class="ct-head">Key</span><span class="ct-head">Auto</span><span></span>
        <template v-for="(column, index) in columns" :key="index">
          <BaseInput v-model="column.name" placeholder="name" />
          <BaseInput v-model="column.dataType" list="pg-create-table-types" placeholder="type" />
          <BaseCheckbox :model-value="!column.nullable" @update:model-value="column.nullable = !$event" />
          <BaseCheckbox v-model="column.primaryKey" />
          <BaseCheckbox v-model="column.identity" title="GENERATED BY DEFAULT AS IDENTITY — for integer columns" />
          <BaseButton icon="trash" size="sm" title="Remove column" @click="removeColumn(index)" />
        </template>
      </div>
      <datalist id="pg-create-table-types">
        <option v-for="type in COMMON_TYPES" :key="type" :value="type" />
      </datalist>
      <BaseButton icon="plus" size="sm" @click="addColumn">Add column</BaseButton>
      <HintText v-if="problem && name">{{ problem }}</HintText>
      <FieldError :text="error" spaced />
    </div>
    <div class="del-footer">
      <span class="spacer"></span>
      <BaseButton @click="emit('close')">Cancel</BaseButton>
      <BaseButton variant="primary" :disabled="!!problem || saving" @click="confirm">
        {{ saving ? 'Creating…' : 'Create' }}
      </BaseButton>
    </div>
  </BaseModal>
</template>

<style scoped>
.ct-grid {
  display: grid;
  grid-template-columns: 1fr 1fr auto auto auto auto;
  gap: 6px 10px;
  align-items: center;
  margin: 12px 0 8px;
}
.ct-head { font-size: 12px; color: var(--text-faint); }
</style>
